---
- name: This is a play
  hosts: all
  vars:
    pubkey: "{{lookup('file', '~/.ssh/id_rsa.pub')}}"
  tasks:

    - name: vm -1 / 1
      virt:
        name: "{{ item.name }}"
        state: destroyed
      ignore_errors: yes
      with_items: "{{ vms[inventory_hostname] }}"

    - name: vm -0 / 1
      virt:
        name: "{{ item.name }}"
        command: undefine
      ignore_errors: yes
      with_items: "{{ vms[inventory_hostname] }}"


    - name: Removing previous cloud init data
      file:
        path: /tmp/cloud-init-data
        state: absent

    - name: Copy cloud-init data
      copy:
        src: cloud-init-data/
        dest: /tmp/cloud-init-data
        
    - name: Copy pub key in he cloud-init data
      template:
        src: cloud-init-data/meta-data
        dest: /tmp/cloud-init-data/meta-data

    - name: Create the iso for cloud-init
      shell: cd /tmp &&  genisoimage -output cloud-init-data.iso -volid cidata -joliet -rock cloud-init-data/user-data cloud-init-data/meta-data


    - name: Copy base image
      shell: "qemu-img create -f qcow2 -o backing_file=/grid5000/virt-images/debian9-x64-base.qcow2 {{ item.backing_file }}"
      with_items: "{{ vms[inventory_hostname] }}"

    - name: vm 0 / 1
      virt:
        name: "{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'domain.xml.j2') }}"
      with_items: "{{ vms[inventory_hostname] }}"


    - name: vm 1 / 1
      virt:
        name: "{{ item.name }}"
        state: running
      with_items: "{{ vms[inventory_hostname] }}"
